[package]
name = "rui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "counter"
]

[workspace.dependencies]
rui = { git = "https://github.com/audulus/rui.git"}