[package]
name = "recipes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
  "clickable_button",
  "clickable_button_native",
  "property_binding",
  "element_animations",
  "animation_sequence",
  "states",
  "transitions",
  "layouts",
  "global_callback",
  "translations",
  "custom_button",
  "custom_switch",
  "custom_slider",
  "custom_slider2",
  "custom_tabs",
  "custom_table",
  "responsive",
]

[workspace.dependencies]
slint = "0.3.5"