[package]
name = "iced"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members=[
    "hello_world",
    "counter",
]

[workspace.dependencies]
iced = "0.8"